name: Check Repository Variable

on: [push, pull_request]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use repository variable
        run: echo "The value of The Token is $APIDOG_ACCESS_TOKEN"
        
      - name: Use repository variable with vars
        run: echo "The value of The Token is ${{ vars.APIDOG_ACCESS_TOKEN }}"